#!/usr/local/bin/node

require.paths.push(__dirname);
require.paths.push(__dirname + "/deps");
require.paths.push(__dirname + "/lib");

var reporter = require("nodeunit").reporters.default;

process.chdir(__dirname);
reporter.run(['test']);