#!/usr/local/bin/node

require.paths.push(__dirname);
require.paths.push(__dirname + "/deps");
require.paths.push(__dirname + "/lib");

var reporter = require("sinon-nodeunit/deps/nodeunit").reporters.skip_passed;

process.chdir(__dirname);
reporter.run(['test', 'test/controllers', 'test/models']);
