#!/usr/local/bin/node

require.paths.push(__dirname);
require.paths.push(__dirname + "/model");
require.paths.push(__dirname + "/lib");

var reporter = require("sinon-nodeunit/deps/nodeunit").reporters.minimal;

process.chdir(__dirname);
reporter.run([
  'test/server', 
  'test/server/controllers', 
  'test/server/model',
  'test/server/events'
]);
